"""Shared dataclasses used across the RAG pipeline.

These are deliberately lightweight (plain dataclasses) and decoupled from the
persistence-layer ``models.domain`` types so the pipeline can be reasoned about
independently of the database schema.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------
@dataclass
class DocumentSection:
    """A raw structural section extracted from a parsed document.

    ``start_offset`` / ``end_offset`` are character offsets into the document's
    canonical full-text string. They are the source of truth: chunk text is
    always sliced from the source using offsets, never generated by an LLM.
    """

    id: str
    page_number: int
    heading: str
    heading_level: int
    start_offset: int
    end_offset: int
    text: str
    is_table: bool = False

    @property
    def token_estimate(self) -> int:
        from rag.tokenization import count_tokens

        return count_tokens(self.text)


@dataclass
class MergedSection:
    """One or more raw sections merged into a single maintenance concept."""

    id: str
    concept_name: str
    section_ids: list[str]
    page_number: int
    start_offset: int
    end_offset: int
    text: str
    heading_level: int = 1
    is_table: bool = False
    # Filled in by downstream agents:
    concept_type: str = "OTHER"
    section_type: str = "OTHER"
    semantic_groups: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Knowledge graph
# ---------------------------------------------------------------------------
@dataclass
class Concept:
    document_id: str
    equipment_id: str | None
    concept_name: str
    concept_type: str
    semantic_groups: list[str] = field(default_factory=list)


@dataclass
class Relationship:
    document_id: str
    equipment_id: str | None
    source: str
    relation: str
    target: str
    concept: str | None = None


# ---------------------------------------------------------------------------
# Chunks
# ---------------------------------------------------------------------------
@dataclass
class Chunk:
    """A parent or child chunk. Text is extracted from source via offsets."""

    chunk_id: str
    document_id: str
    equipment_id: str | None
    equipment_type: str | None
    document_type: str | None
    concept: str | None
    semantic_type: str
    page: int
    start_offset: int
    end_offset: int
    text: str
    is_parent: bool
    parent_chunk_id: str | None = None
    token_count: int = 0
    is_table: bool = False
    created_at: datetime | None = None


# ---------------------------------------------------------------------------
# Special structured extractions
# ---------------------------------------------------------------------------
@dataclass
class IncidentRecord:
    """Structured failure-report extraction (Incident Knowledge Base)."""

    id: str
    document_id: str
    equipment_id: str | None
    failure_mode: str
    symptoms: list[str]
    root_cause: str
    resolution: str
    outcome: str
    created_at: datetime | None = None

    def as_text(self) -> str:
        symptoms = ", ".join(self.symptoms) if self.symptoms else "n/a"
        return (
            f"Failure mode: {self.failure_mode}. Symptoms: {symptoms}. "
            f"Root cause: {self.root_cause}. Resolution: {self.resolution}. "
            f"Outcome: {self.outcome}."
        )


@dataclass
class MaintenanceLogRecord:
    """Structured maintenance-log extraction."""

    id: str
    document_id: str
    equipment_id: str | None
    symptom: str
    action: str
    result: str
    created_at: datetime | None = None

    def as_text(self) -> str:
        return (
            f"Symptom: {self.symptom}. Action: {self.action}. "
            f"Result: {self.result}."
        )


# ---------------------------------------------------------------------------
# Search
# ---------------------------------------------------------------------------
@dataclass
class RetrievedItem:
    """A single hit returned from a vector index, plus scoring metadata."""

    kind: str  # "chunk" | "incident" | "maintenance_log"
    ref_id: str
    index_name: str
    semantic_score: float
    payload: dict[str, Any] = field(default_factory=dict)
    # Sparse/lexical (BM25) similarity for the same item, in [0, 1]. Populated by
    # the hybrid retrieval path so exact codes / part numbers / fault codes that
    # dense embeddings under-weight still rank. Defaults to 0.0 for dense-only.
    lexical_score: float = 0.0
    # Hybrid-ranking components (populated during ranking):
    metadata_score: float = 0.0
    equipment_score: float = 0.0
    recency_score: float = 0.0
    final_score: float = 0.0
    rerank_score: float | None = None
